# Generated by Django 4.2.13 on 2024-05-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100)),
                ('descripcion_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='desarrolador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desarrolador', models.CharField(max_length=100)),
                ('apellido_desarrolador', models.CharField(max_length=100)),
                ('rol_desarrolador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
        ),
    ]
