# Generated by Django 4.2.13 on 2024-05-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('desarrolador_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.desarrolador')),
            ],
        ),
    ]
